### ISSUE TITLE
Thank you JK!!!

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/Grisu-Exact#12]
You have developed a new string to float algorithm? Great! Have you tried my method for providing infinite precision of floating-point parsing?

**Comment by jk-jeon** [comment]
I developed one that works with a precision limit, but I guess it would be not so different from Ryu-stof. There is way less room of creativity compared to the ftos counterpart. Especially, the conversion from decimal to binary is sorta... obvious.

While string-to-decimal parsing may have a lot of room for improvement, I still prefer to work with decimal floating-point data rather than to work with character strings directly, so my focus is mainly on decimal-to-binary conversion. I want those two steps to be cleanly separated as much as possible, though I'm not sure if that will help or hurt the overall performance.

I'm currently digging into Ryu-printf so that I can use it for infinite precision stof we've talked about without having to first generate a long character string.

I will close this and inform you (if you want) when I make a tangible progress.

**Comment by expnkx** [comment]
> I developed one that works with a precision limit, but I guess it would be not so different from Ryu-stof. There is way less room of creativity compared to the ftos counterpart. Especially, the conversion from decimal to binary is sorta... obvious.
> 
> While string-to-decimal parsing may have a lot of room for improvement, I still prefer to work with decimal floating-point data rather than to work with character strings directly, so my focus is mainly on decimal-to-binary conversion. I want those two steps to be cleanly separated as much as possible, though I'm not sure if that will help or hurt the overall performance.
> 
> I'm currently digging into Ryu-printf so that I can use it for infinite precision stof we've talked about without having to first generate a long character string.
> 
> I will close this and inform you (if you want) when I make a tangible progress.

For over 17 digits, at least you can deal with the special case!

https://github.com/expnkx/fast_io/blob/41f62bb9055ec9b4853078b9d2df7b3f4f98f996/include/fast_io_freestanding_impl/floating_point/ryu/sto_reserve.h#L267

BTW. I have solved the issue of how to make input buffer also contiguous instead of abusing stream model. That speeds up performance for another 10%-20%

**Comment by jk-jeon** [comment]
>For over 17 digits, at least you can just deal with the special case { f(m10+1,e10)==f(m10,e10) }! That will make at least 50% of infinite precision input work.

You are right. (I'm not sure about the percentage though:))

**Comment by jk-jeon** [comment]
> BTW. I have solved the issue of how to make input buffer also contiguous instead of abusing stream model. That speeds up performance for another 10%-20%

Out of curiosity. What does it mean?

**Comment by expnkx** [comment]
> > BTW. I have solved the issue of how to make input buffer also contiguous instead of abusing stream model. That speeds up performance for another 10%-20%
> 
> Out of curiosity. What does it mean?

Did you remember the question you asked me how to solve the issue of dealing with bounds problem? The solution is that these algorithms are stream-friendly (since stream is an abstraction that can deal with an infinite amount of output data) instead of string model. I just make all these formatting algorithms being dealt with directly on the output buffer.

string in general just sucks tbh.

The reverse problem is how to deal with it with raw bytes on the input buffer. I have solved that part of the issue recently. The parsing algorithm will directly deal with contiguous iterators or random access iterator instead of input iterator.

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/90201884-239ea600-ddaa-11ea-892c-f59b9192546b.png)

**Comment by expnkx** [comment]
https://github.com/expnkx/fast_io/blob/41f62bb9055ec9b4853078b9d2df7b3f4f98f996/include/fast_io_core_impl/print_scan.h#L75
![image](https://user-images.githubusercontent.com/57303909/90202019-79734e00-ddaa-11ea-8170-80fa24623a27.png)

**Comment by jk-jeon** [comment]
Hmm, I think I didn't understand the issue correctly.

1. So for the output side, what do you do after printing the contents into a temporary buffer? Do you copy it back to the output buffer? If that's the case, what do you do if the contents to copy back is longer than the remaining space of the output buffer?

2. What exactly is the issue of the input side? Is it about incomplete input data?

**Comment by expnkx** [comment]
> Hmm, I think I didn't understand the issue correctly.
> 
> 1. So for the output side, what do you do after printing the contents into a temporary buffer? Do you copy it back to the output buffer? If that's the case, what do you do if the contents to copy back is longer than the remaining space of the output buffer?

It will call I/O operation write(output,array.begin(),array.end()); The write function knows how to deal with truncating data.

> 2. What exactly is the issue of the input side? Is it about incomplete input data?

YES!

**Comment by jk-jeon** [comment]
>It will call I/O operation write(output,array.begin(),array.end()); The write function knows how to deal with truncating data. It is output stream dependent. (fast_io is concepts based library, the user can define the behavior of everything whatever they want as long as they satisfied the concepts)

Aha.

>YES!

So how a temporary buffer can help?

**Comment by expnkx** [comment]
> So how a temporary buffer can help?

Make it contiguous.

**Comment by jk-jeon** [comment]
I think I'm not getting it? So what do you do exactly? Wait for the input to be completed? Sorry for a dumb question though

**Comment by expnkx** [comment]
> I think I'm not getting it? So what do you do exactly? Wait for the input to be completed? Sorry for a dumb question though

The type tells how to end the algorithm and tells how to transmit data to make it complete.

**Comment by expnkx** [comment]
See this:

https://github.com/expnkx/fast_io/commit/51eade78a26ed6ac8b14f5c17ed47f923e20e7f8

https://github.com/expnkx/fast_io/blob/master/benchmarks/0027.pmr_push_back/monotonic_io_buffer_vector.cc
https://github.com/expnkx/fast_io/blob/master/benchmarks/0027.pmr_push_back/vector.cc

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/90255726-ab1fff80-de12-11ea-8185-bab189d8def8.png)
BTW. How did you draw these plots?

**Comment by expnkx** [comment]
Jk. Can you help me view my paper?

**Comment by jk-jeon** [comment]
>BTW. How did you draw these plots?

I used MATLAB (`scatter` function) to draw the plots. The source code is here: https://github.com/jk-jeon/Grisu-Exact/blob/master/benchmark_results/plot_uniform_benchmark.m

>Jk. Can you help me view my paper?

What do you mean?
