### ISSUE TITLE
input the value 0. It produces 0e-307??

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/Grisu-Exact#3]
ryu generates exactly 0 but this generates 0e-307? Am I doing something wrong?
D:\hg\w4\fast_io\testsuites\0001.grisu>grisu_exact
0
0
0e-307

**Comment by jk-jeon** [comment]
I think I should look at your implementation to know further, but let me explain a little bit before diving into your implementation.

If you look at the implementation of `jkj::fp_to_chars`, it actually treat 0 specially; it just directly writes `0E0` to the buffer, just like Ryu does. `jkj::grisu_exact` itself does not care about 0, infinities, nor NaN's. (But as you have seen, it produces 0e-307 from 0, which is technically a "correct" output.) Those special cases should be treated separately in an upper-layer function. This is an intended design choice, and `jkj::bit_representation_t<Float>` is a helper class that one might use for detecting those special cases.

**Comment by expnkx** [comment]
> I think I should look at your implementation to know further, but let me explain a little bit before diving into your implementation.
> 
> If you look at the implementation of `jkj::fp_to_chars`, it actually treat 0 specially; it just directly writes `0E0` to the buffer, just like Ryu does. `jkj::grisu_exact` itself does not care about 0, infinities, nor NaN's. (But as you have seen, it produces 0e-307 from 0, which is technically a "correct" output.) Those special cases should be treated separately in an upper-layer function. This is an intended design choice, and `jkj::bit_representation_t<Float>` is a helper class that one might use for detecting those special cases.

Ok. Here is the latest GCC compiler you can use to build my library on windows.
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

BTW. I did not use your fp_to_chars since what I need is the shorter one between scientific and fixed which is %g does. This part is copied from my ryu code.

**Comment by jk-jeon** [comment]
Yeah, I know you didn't use `jkj::fp_to_chars`.

>https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

Okay, I will try that compiler.
