### ISSUE TITLE
Hello JK. Another question for you so I might replace ryu with your algorithm since your table looks smaller?

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/Grisu-Exact#7]
Do you have an efficient string to floating-point algorithm based on Grisu-Exact? It looks like the process could be reversed as long as the precision is not beyond the range of floating-point.

**Comment by jk-jeon** [comment]
Short answer: No.

Long answer:
I think it will be possible to invert what Grisu-Exact is doing by again using the Grisu-like idea with the Ryu's magic for mathematically proving sufficiency of certain precision. I was actually thinking of it this January, but never really worked out.

As far as I know, Ulf already did something similar and implemented a string-to-float routine, and actually what he was considering is something even more general.

I think when I was thinking of the decimal-to-binary conversion (which is the core of string-to-float) I had been thinking that it should be simpler than binary-to-decimal for some reason, but now I can't recall the exact reason.

My current guess is that if I really work out, I might be able to develop a new algorithm for decimal-to-binary conversion, but it will take a considerable amount of effort (if not impossible) to beat what' currently offered by Ryu, in terms of performance.

Right now, I have no plan for actually doing it. But if you are really interested in it, maybe you can read the Grisu-Exact paper and discuss it with me. By doing so, you might get the idea of how to do the reverse. As far as I remember, the core idea was not that difficult to come up with once you understand Grisu-Exact.
